# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 19:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200, verbose_name='name of the merchant')),
                ('price', models.CharField(max_length=200, verbose_name='price')),
                ('date', models.CharField(default=datetime.datetime(2016, 5, 17, 19, 41, 25, 105083), max_length=200, verbose_name='date of receipt')),
                ('status_receipt', models.CharField(default='disapproved', max_length=200, verbose_name='status of receipt')),
                ('receipt', models.ImageField(default='default.png', upload_to='static/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Receipt',
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipt',
            },
        ),
    ]
