# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 5, 18, 3, 22, 3, 257437), max_length=200, verbose_name='date of receipt'),
        ),
    ]
